common:
  lid_topic: "/os_cloud_node/points"
  imu_topic: "/stim300/imu/data_raw"

  acc_cov: 1.1501915187049582e-03 # acc noise and bias
  b_acc_cov: 3.729854069064516e-05
  gyr_cov: 5.084312924828687e-05  # gyro noise and bias
  b_gyr_cov: 6.509823412408377e-07

  extrinsic_T: [ -0.036897, 0.00787575, -0.0228079 ]    # from lidar to imu
  extrinsic_R: [ 0.9999765, -0.0023318, -0.0064528,
                 0.0022921,  0.9999785, -0.0061474,
                 0.0064670,  0.0061325,  0.9999603 ]

  odom_link: "camera_init"
  scan_filter_size: 0.1
  map_viewer_size: 0.4
  map_saved_size: 0.1

  useImuFrame: false                        # when we use imu frame, we will get dense color cloud
  useLoopClosure: false                     # if we enable loop clouser                    # 40 for indoors and 60m for outdoors

  saveResultBag: false
  saveResultBodyFrame: true
  saveKeyFrame: false                       # include color point cloud frame and raw distorted point cloud

  # corridor_day
  initial_pose: [ 0.96644286559409200649, -0.25685421425740788204, 0.003751062431636435972, 5.2711577417659201819,
                  0.2557153541051056066, 0.96334248524454570928, 0.081122654191151540328, -1.1168942975664494433,
                  -0.024450250723975192019, -0.077441211946613232512, 0.99669706976879401463, 1.3392035133175538313,
                  0, 0, 0, 1 ]

lio:
  lidar_type: 3                          # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
  scan_line: 128
  scan_rate: 10                         # only need to be set for velodyne, unit: Hz,
  timestamp_unit: 0                     # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
  blind: 0.5                            # remove the nearest point cloud

  fov_degree: 180
  det_range: 150.0

  point_filter_num: 3
  max_iteration: 3
  filter_size_corner: 0.1
  filter_size_surf: 0.1
  filter_size_map: 0.2
  cube_side_length: 1000

pgo:
  SKIP_FRAMES: 5                                    # map visualization, every x frame we add it in the globalmap and publish it
  useRawCloud: false
  showDegenercy: true                              # show condition number or uncertainty in rviz

  useGlobalPrior: true
  map_filter_size: 0.5                             # indoor:0.1, outdoor:0.2
  icpO3dType: 2                                    # 0: icp 1:point2plane 2:gicp
  degeneracy_thres: 50
  correspondence_dis: 1.0                          # stair_bob: 0.6;
  map_radius: 50

  loopZOffset: 5.0                                # for escaltor
  historyKeyframeSearchRadius: 5.0
  historyKeyframeSearchTimeDiff: 40.0
  historyKeyframeSearchNum: 25
  loopFitnessScoreThreshold: 0.3
  loopClosureFrequency: 1                         # if you want to detect more loop, you can set it larger

  filterDis: 0.5                                  #  did not add loop if the distance of consecutive node less than 10m
  filterNodeNum: 10
