common:
  lid_topic: "/velodyne_points"
  imu_topic: "/imu/data"

  acc_cov: 1.0481546278947311e-02  # acc noise and bias
  b_acc_cov: 1.8451561389195461e-04
  gyr_cov: 9.6690835928856730e-03   # gyro noise and bias
  b_gyr_cov: 8.2887875865635737e-05

  extrinsic_T: [ 0.0961, -0.1338, 0.3032 ]    # from lidar to imu
  extrinsic_R: [ 0.9999,0.0049, 0.0153,
                 -0.0050, 1.0000, 0.0021,
                 -0.0153, -0.0022, 0.9999]

  odom_link: "camera_init"
  scan_filter_size: 0.1
  map_viewer_size: 0.2
  map_saved_size: 0.1

  useImuFrame: false                        # when we use imu frame, we will get dense color cloud
  useLoopClosure: true                      # if we enable loop clouser

  # save data
  saveResultBag: false
  saveResultBodyFrame: true
  saveKeyFrame: false                     # include color point cloud frame and raw distorted point cloud

  initial_pose: [ -0.519301, 0.850557, 0.082936 ,-11.347226,
                  -0.852164, -0.522691, 0.024698, 3.002144,
                  0.064357, -0.057849, 0.996249, -0.715776,
                  0.000000, 0.000000, 0.000000, 1.000000 ]


lio:
  lidar_type: 2                          # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
  scan_line: 16
  scan_rate: 10                         # only need to be set for velodyne, unit: Hz,
  timestamp_unit: 0                     # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
  blind: 0.5                            # remove the nearest point cloud

  fov_degree: 180
  det_range: 150.0

  point_filter_num: 1
  max_iteration: 3
  filter_size_corner: 0.1
  filter_size_surf: 0.1
  filter_size_map: 0.2
  cube_side_length: 1000

pgo:
  SKIP_FRAMES: 5                                    # map visualization, every x frame we add it in the globalmap and publish it
  useRawCloud: true
  showDegenercy: false                             # false: show uncertainty; true: show degeneracy

  useGlobalPrior: true
  icpO3dType: 2                                    # 0: icp 1:point2plane 2:gicp
  degeneracy_thres: 50
  correspondence_dis: 0.8                          # stair_bob: 0.6;
  map_radius: 40
  map_filter_size: 0.1                             # indoor:0.1, outdoor:0.2

  loopZOffset: 2.0                                 # for stairs, if z_offset is larger than 2.0, we do not detect loop
  historyKeyframeSearchRadius: 10.0
  historyKeyframeSearchTimeDiff: 40.0
  historyKeyframeSearchNum: 25
  loopFitnessScoreThreshold: 0.3
  loopClosureFrequency: 1                         # if you want to detect more loop, you can set it larger
  filterDis: 0.5                                  #  did not add loop if the distance of consecutive node less than 10m
  filterNodeNum: 10                               #  did not detect loop every 10 nodes for ecah loop detetcion method


